name: Deploy broker

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script_stop: true
          script: |
            set -e
          
            echo "PROJECT_PATH=${{ secrets.PROJECT_PATH }}"
          
            cd ${{ secrets.PROJECT_PATH }}
          
            echo "Current directory:"
            pwd
          
            echo "Git remote:"
            git remote -v
          
            echo "Git status:"
            git status
          
            git fetch origin
            git reset --hard origin/main
            git clean -fd
          
            npm install
            npm run build
